language: android
before_script:
    - touch local.properties
    - echo "n" | android create avd --force -n test -t "android-24" -c 100M --abi "default/armeabi-v7a"
    - emulator -avd test -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

android:
    components:
        - tools
        - build-tools-28.0.3
        - android-28
        - android-24
        - sys-img-armeabi-v7a-android-24

script:
    - ./gradlew build :app:connectedCheck
